version: "3.2"
services:

  database:
    image: 'postgres:latest'
    container_name: 'doc_storage'

    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - ${POSTGRES_PORT}:5432

    volumes:
      - ./.database_data:/var/lib/postgresql/data

  # app:
    # container_name: ${DOCKER_APP_NAME}
    # build: ./service

    # environment:
    #   - POSTGRES_HOST=database
    #   - DATABASE_NAME=${DATABASE_NAME}
    #   - DATABASE_USERNAME=${DATABASE_USERNAME}
    #   - POSTGRES_PORT=5432
    #   - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    #   - APP_PORT=${APP_PORT}
    # ports:
    #   - 8765:${APP_PORT}
    # depends_on:
    #   - database
